server.port=8080
spring.application.name=ecom-monolith

# H2 — une seule base pour les deux entités
spring.datasource.url=jdbc:h2:mem:ecom-db
spring.h2.console.enabled=true

management.endpoints.web.exposure.include=*
